<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../Shared/Shared.Kernel/Shared.Kernel.csproj" />
    <ProjectReference Include="../Notifications.Domain/Notifications.Domain.csproj" />
    <ProjectReference Include="../Notifications.Contracts/Notifications.Contracts.csproj" />
    <ProjectReference Include="../../Identity/Identity.Contracts/Identity.Contracts.csproj" />
    <ProjectReference Include="../../Students/Students.Contracts/Students.Contracts.csproj" />
    <ProjectReference Include="../../Teachers/Teachers.Contracts/Teachers.Contracts.csproj" />
    <ProjectReference Include="../../Enrollments/Enrollments.Contracts/Enrollments.Contracts.csproj" />
    <ProjectReference Include="../../Billing/Billing.Contracts/Billing.Contracts.csproj" />
    <ProjectReference Include="../../Scheduling/Scheduling.Contracts/Scheduling.Contracts.csproj" />
  </ItemGroup>

</Project>
