<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Identity/Identity.Contracts/Identity.Contracts.csproj" />
    <ProjectReference Include="../../Students/Students.Contracts/Students.Contracts.csproj" />
    <ProjectReference Include="../../Teachers/Teachers.Contracts/Teachers.Contracts.csproj" />
    <ProjectReference Include="../../Enrollments/Enrollments.Contracts/Enrollments.Contracts.csproj" />
    <ProjectReference Include="../../Courses/Courses.Contracts/Courses.Contracts.csproj" />
    <ProjectReference Include="../../Billing/Billing.Contracts/Billing.Contracts.csproj" />
  </ItemGroup>

</Project>
