<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../Shared/Shared.Kernel/Shared.Kernel.csproj" />
    <ProjectReference Include="../Teachers.Domain/Teachers.Domain.csproj" />
    <ProjectReference Include="..\..\Identity\Identity.Contracts\Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\Students\Students.Contracts\Students.Contracts.csproj" />
  </ItemGroup>

</Project>
