namespace Shared.Kernel.Abstractions;

// Where uploaded files live. Names are always generated by the storage, never taken from the client,
// so an uploaded file can never end up outside its folder. The database keeps only the returned key.
public interface IFileStorage
{
    // Stores the content as <folder>/<new unique name><extension> and returns that key
    Task<string> SaveAsync(string folder, string extension, Stream content, CancellationToken ct = default);

    // null when there is no such file
    Task<Stream?> OpenReadAsync(string key, CancellationToken ct = default);

    // Deleting a file that does not exist is not an error
    Task DeleteAsync(string key, CancellationToken ct = default);
}
